# Generated by Django 4.0.5 on 2022-08-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('teacher', models.CharField(blank=True, max_length=40)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('start', models.TimeField(blank=True)),
                ('end', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.IntegerField(blank=True, null=True)),
                ('class_number', models.IntegerField(blank=True, null=True)),
                ('fri', models.ManyToManyField(blank=True, related_name='fri', to='Timetable.tablecell')),
                ('mon', models.ManyToManyField(blank=True, related_name='mon', to='Timetable.tablecell')),
                ('set', models.ManyToManyField(blank=True, related_name='set', to='Timetable.tablecell')),
                ('sun', models.ManyToManyField(blank=True, related_name='sun', to='Timetable.tablecell')),
                ('thu', models.ManyToManyField(blank=True, related_name='thu', to='Timetable.tablecell')),
                ('tue', models.ManyToManyField(blank=True, related_name='tue', to='Timetable.tablecell')),
                ('wed', models.ManyToManyField(blank=True, related_name='wed', to='Timetable.tablecell')),
            ],
        ),
    ]
